### ISSUE TITLE
Prooph\EventStore\Exception\CannotEstablishConnection Cannot resolve target end point

### ISSUE THREAD

**Issue by majidalaeinia** [prooph/event-store-client#164]
I use this `docker-compose.yml` file to run services:

```yaml
version: '3.5'

services:
    ## --------------------------------------------
    ## | 1: APP Web Server Php7 and required Extensions
    ## --------------------------------------------
    web:
        container_name: ${APP_NAME}_${APP_ENV}_web
        build:
            context: ./docker/web
            dockerfile: Dockerfile
            args:
                - WWW_DATA_USER=${APP_UID}
                - WWW_DATA_GROUP=${APP_GID}
                - ENVIRONMENT=${APP_ENV}
        restart: unless-stopped
        expose:
            - "80"
            - "443"

        volumes:
            - ./:/var/www/
            - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/web/site.conf:/etc/nginx/sites-enabled/site.conf
        ports:
            - "23080:80"

        networks:
            - cqrs-write-read_local_network

    ## --------------------------------------------
    ## | 2: APP Web Server Php7 and required Extensions
    ## --------------------------------------------
    php:
        container_name: ${APP_NAME}_${APP_ENV}_php
        build:
            context: ./docker/php
            dockerfile: Dockerfile
            args:
                - WWW_DATA_USER=${APP_UID}
                - WWW_DATA_GROUP=${APP_GID}
                - ENVIRONMENT=${APP_ENV}
        restart: unless-stopped
        expose:
            - "9000"

        volumes:
            - ./:/var/www/
            - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
            - ./docker/php/php_prod.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./docker/php/log/supervisord/:/var/log/supervisord/

        networks:
            - cqrs-write-read_local_network

    ## --------------------------------------------
    ## |  3: Redis Instance
    ## --------------------------------------------
    redis:
        container_name: ${APP_NAME}_${APP_ENV}_redis
        image: redis:5.0.7
        restart: unless-stopped
        ports:
            - "127.0.0.1:23085:6380"
        volumes:
            - redis_data:/data

        networks:
            - cqrs-write-read_local_network

    ## --------------------------------------------
    ## | 4: database server
    ## --------------------------------------------
    mysql:
        container_name: ${APP_NAME}_${APP_ENV}_mysql
        build:
            context: ./docker/mysql
            dockerfile: Dockerfile
            args:
                - UID=${APP_UID}
                - GID=${APP_GID}

        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - "23008:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker/mysql/config.ini:/etc/mysql/conf.d/config.ini

    ## --------------------------------------------
    ## | 5: PhpMyAdmin
    ## --------------------------------------------
    phpmyadmin:
        container_name: ${APP_NAME}_${APP_ENV}_phpmyadmin
        image: phpmyadmin/phpmyadmin:5.0.1
        restart: unless-stopped
        depends_on:
            - mysql
        ports:
            - "23005:80"
        environment:
            - PMA_HOST=mysql
        volumes:
            - /sessions
            - ./docker/phpmyadmin/save/:/var/www/phpmyadmin/save/
            - ./docker/phpmyadmin/upload/:/var/www/phpmyadmin/upload/
            - ./docker/phpmyadmin/config.php:/etc/phpmyadmin/config.user.inc.php

    ## --------------------------------------------
    ## | 6: ZooKeeper
    ## --------------------------------------------
    zookeeper:
        container_name: ${APP_NAME}_${APP_ENV}_zookeeper
        image: confluentinc/cp-zookeeper:latest
        restart: unless-stopped
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 22181:2181
        networks:
            - cqrs-write-read_local_network

    ## --------------------------------------------
    ## | 7: Kafka
    ## --------------------------------------------
    kafka:
        container_name: ${APP_NAME}_${APP_ENV}_kafka
        image: confluentinc/cp-kafka:latest
        restart: unless-stopped
        depends_on:
            - zookeeper
        ports:
            - 29092:29092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        networks:
            - cqrs-write-read_local_network

    ## --------------------------------------------
    ## | 8: Event Store
    ## --------------------------------------------
    eventstoredb:
        container_name: ${APP_NAME}_${APP_ENV}_eventstoredb
        image: eventstore/eventstore:20.10.2-buster-slim
        restart: unless-stopped
        environment:
            - EVENTSTORE_CLUSTER_SIZE=1
            - EVENTSTORE_RUN_PROJECTIONS=All
            - EVENTSTORE_START_STANDARD_PROJECTIONS=true
            - EVENTSTORE_EXT_TCP_PORT=1113
            - EVENTSTORE_HTTP_PORT=2113
            - EVENTSTORE_INSECURE=true
            - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
            - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
        ports:
            - "1113:1113"
            - "2113:2113"
        volumes:
          - type: volume
            source: eventstore-volume-data
            target: /var/lib/eventstore
          - type: volume
            source: eventstore-volume-logs
            target: /var/log/eventstore

        networks:
            - cqrs-write-read_local_network

volumes:
    redis_data:
        driver: local

    mysql_data:
        driver: local

    eventstore-volume-data:
    eventstore-volume-logs:

networks:
    cqrs-write-read_local_network:
        external: true
```  
And here is the output of the `docker ps` command:  
```bash
CONTAINER ID   IMAGE                                       COMMAND                  CREATED          STATUS                    PORTS                                                                                                      NAMES
395ec8913d9e   confluentinc/cp-kafka:latest                "/etc/confluent/dock…"   4 seconds ago    Up 3 seconds              9092/tcp, 0.0.0.0:29092->29092/tcp, :::29092->29092/tcp                                                    cqrs-write-read_local_kafka
50046bb13d32   cqrs-write-read_php                         "docker-php-entrypoi…"   6 seconds ago    Up 5 seconds              9000/tcp                                                                                                   cqrs-write-read_local_php
e8261e7fb7df   eventstore/eventstore:20.10.2-buster-slim   "/opt/eventstore/eve…"   15 seconds ago   Up 14 seconds (healthy)   1112/tcp, 0.0.0.0:1113->1113/tcp, :::1113->1113/tcp, 2112/tcp, 0.0.0.0:2113->2113/tcp, :::2113->2113/tcp   cqrs-write-read_local_eventstoredb
fd53198bf2ed   confluentinc/cp-zookeeper:latest            "/etc/confluent/dock…"   15 seconds ago   Up 14 seconds             2888/tcp, 3888/tcp, 0.0.0.0:22181->2181/tcp, :::22181->2181/tcp                                            cqrs-write-read_local_zookeeper
77cc65ec1e4e   cqrs-write-read_web                         "nginx -g 'daemon of…"   16 seconds ago   Up 4 seconds              0.0.0.0:23080->80/tcp, :::23080->80/tcp                                                                    cqrs-write-read_local_web
26c04b96f585   phpmyadmin/phpmyadmin:5.0.1                 "/docker-entrypoint.…"   18 minutes ago   Up 18 minutes             0.0.0.0:23005->80/tcp, :::23005->80/tcp                                                                    cqrs-write-read_local_phpmyadmin
cb88ecf2c324   redis:5.0.7                                 "docker-entrypoint.s…"   18 minutes ago   Up 18 minutes             6379/tcp, 127.0.0.1:23085->6380/tcp                                                                        cqrs-write-read_local_redis
9c53104f31e5   cqrs-write-read_mysql                       "docker-entrypoint.s…"   18 minutes ago   Up 18 minutes             33060/tcp, 0.0.0.0:23008->3306/tcp, :::23008->3306/tcp                                                     cqrs-write-read_local_mysql

```
I try to run this code (from the examples):
```php
public function test()
{
        Loop::run(function () {
            $builder = new ConnectionSettingsBuilder();
            $builder->setGossipSeedEndPoints([
                new EndPoint('localhost', 2113),
                //new EndPoint('localhost', 2123),
                //new EndPoint('localhost', 2133),
            ]);

            Log::info(1);

            $connection = EventStoreConnectionFactory::createFromSettings(
                $builder->build(),
                'cluster-connection'
            );



            Log::info(2);

            $connection->onConnected(function (): void {
                echo 'connected' . PHP_EOL;
            });

            Log::info(3);

            $connection->onClosed(function (): void {
                echo 'connection closed' . PHP_EOL;
            });

            Log::info(4);

            yield $connection->connectAsync();

            Log::info(5);

            $slice = yield $connection->readStreamEventsForwardAsync(
                'foo-bar',
                10,
                2,
                true
            );

            \var_dump($slice);

            $slice = yield $connection->readStreamEventsBackwardAsync(
                'foo-bar',
                10,
                2,
                true
            );

            \var_dump($slice);

            $event = yield $connection->readEventAsync('foo-bar', 2, true);

            \var_dump($event);

            $m = yield $connection->getStreamMetadataAsync('foo-bar');

            \var_dump($m);

            $r = yield $connection->setStreamMetadataAsync('foo-bar', ExpectedVersion::ANY, new StreamMetadata(
                null, null, null, null, null, [
                    'foo' => 'bar',
                ]
            ));

            \var_dump($r);

            $m = yield $connection->getStreamMetadataAsync('foo-bar');

            \var_dump($m);

            $wr = yield $connection->appendToStreamAsync('foo-bar', ExpectedVersion::ANY, [
                new EventData(EventId::generate(), 'test-type', false, 'jfkhksdfhsds', 'meta'),
                new EventData(EventId::generate(), 'test-type2', false, 'kldjfls', 'meta'),
                new EventData(EventId::generate(), 'test-type3', false, 'aaa', 'meta'),
                new EventData(EventId::generate(), 'test-type4', false, 'bbb', 'meta'),
            ]);

            \var_dump($wr);

            $ae = yield $connection->readAllEventsForwardAsync(Position::start(), 2, false, new UserCredentials(
                'admin',
                'changeit'
            ));

            \var_dump($ae);

            $aeb = yield $connection->readAllEventsBackwardAsync(Position::end(), 2, false, new UserCredentials(
                'admin',
                'changeit'
            ));

            \var_dump($aeb);

            $connection->close();
        });
}
```

But I get this error:
```bash
Prooph\EventStore\Exception\CannotEstablishConnection
Cannot resolve target end point
```
